version: "3.9"
services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_DB: "lab2"
      POSTGRES_USER: "test"
      POSTGRES_PASSWORD: "test"
    ports:
      - "5434:5432"
    restart: always
    volumes:
      - ./migrations/init.sql:/docker-entrypoint-initdb.d/init.sql