version: "3.9"
services:
  #shop:
  #  build:
  #    context: .
  # ports:
  #  - "8081:8081"
  #depends_on:
  #   - db_mongo
  db_mongo:
    image: mongo
    ports:
      - "27017:27017"
    restart: always
    volumes:
      - ./migrations/init-mongo.js:/docker-entrypoint-initdb.d/init-mongo.js
      - ./migrations/records.json:/records.json
      #  - ./migrations/init-mongo.js:/docker-entrypoint-initdb.d/init-mongo.js
  redis:
    image: redis:alpine
    ports:
      - '6379:6379'